### PR TITLE
The latest Login

### PR DESCRIPTION
**Pull request by klay964**
login modal for login

### CODE REVIEW

**Comment by klay964** [comment]
@MuhannedNoman  you can check it now

**Comment by MuhannedNoman** [comment]
This should resolve #53

**Comment by MuhannedNoman** [comment]
This has an old version of NavBar so I will wait for that to be merged #62    and then merge this!

**Comment by MuhannedNoman** [comment]
Hey @klay964 , nice work here. Can you please check why the Login test is failing. Thank you!

**Pull request merged**
